spring.application.name=greentechbackend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/greentech
spring.datasource.username=jdbcuser
spring.datasource.password=cancerkid123