spring.application.name=backend

# CUSTOM ESAME:
# cambia "esame" con il nome del database della traccia.
# Se usi MySQL locale, crea prima il database oppure abilita createDatabaseIfNotExist nell'URL.
spring.datasource.url=jdbc:mysql://localhost:3306/esame
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
